import {
  Document, Page, Text, View,
  StyleSheet, pdf, Font
} from '@react-pdf/renderer'
import type { Question } from '@/types'

const styles = StyleSheet.create({
  page: {
    paddingTop: 60, // Increased to avoid overlap with fixed header
    paddingBottom: 60,
    paddingHorizontal: 54,
    fontFamily: 'Times-Roman',
    fontSize: 11,
  },
  header: {
    position: 'absolute', // Absolute positioning for fixed elements
    top: 30,
    left: 54,
    right: 54,
    borderBottomWidth: 1,
    borderBottomColor: '#000',
    paddingBottom: 10,
    marginBottom: 20,
  },
  title: {
    fontSize: 14, // Slightly smaller for better fit
    fontFamily: 'Times-Bold',
    textAlign: 'center',
    marginBottom: 2,
  },
  subtitle: {
    fontSize: 9,
    textAlign: 'center',
    color: '#555',
    marginBottom: 4,
  },
  instructions: {
    fontSize: 8,
    color: '#666',
    lineHeight: 1.4,
    textAlign: 'center',
  },
  questionBlock: {
    marginBottom: 20,
    paddingTop: 10, // Gives breathing room between questions
  },
  topicTag: {
    fontSize: 7,
    textTransform: 'uppercase',
    color: '#777',
    marginBottom: 2,
  },
  questionLabel: {
    fontSize: 10,
    fontFamily: 'Times-Bold',
    marginBottom: 3,
  },
  stem: {
    fontSize: 11,
    lineHeight: 1.5,
    marginBottom: 8,
  },
  option: {
    fontSize: 10,
    marginLeft: 20,
    marginBottom: 3,
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 54,
    right: 54,
    flexDirection: 'row',
    justifyContent: 'space-between',
    fontSize: 8,
    color: '#999',
    borderTopWidth: 0.5,
    borderTopColor: '#ccc',
    paddingTop: 6,
  },
})

// Component for the PDF Structure
export const ExamPDFDocument = ({
  questions,
  title = 'Medical Sciences — Practice Paper',
}: {
  questions: Question[]
  title?: string
}) => (
  <Document>
    <Page size="A4" style={styles.page}>
      
      {/* If you want the full instructions ONLY on Page 1, 
          remove 'fixed' and move it inside the flow. 
          If you want a condensed header on every page, keep 'fixed'.
      */}
      <View style={styles.header} fixed>
        <Text style={styles.title}>{title}</Text>
        <Text style={styles.subtitle}>
          {questions.length} Questions  |  {Math.ceil(questions.length * 1.2)} Minutes
        </Text>
      </View>

      {/* Questions Flow */}
      {questions.map((q, i) => (
        <View key={q.id} style={styles.questionBlock} wrap={false}>
          <Text style={styles.topicTag}>{q.topic} › {q.subtopic}</Text>
          <Text style={styles.questionLabel}>Question {i + 1}</Text>
          <Text style={styles.stem}>{q.question}</Text>
          
          {/* Sorting keys to ensure A, B, C order */}
          {Object.entries(q.options)
            .sort(([a], [b]) => a.localeCompare(b))
            .map(([letter, text]) => (
              <Text key={letter} style={styles.option}>
                {letter}.  {text}
              </Text>
            ))
          }
        </View>
      ))}

      {/* Page footer */}
      <View style={styles.footer} fixed>
        <Text>Generated by Yeen Practice Systems</Text>
        <Text render={({ pageNumber, totalPages }) => (
          `Page ${pageNumber} of ${totalPages}`
        )} />
      </View>
    </Page>
  </Document>
)

export async function downloadExamPDF(
  questions: Question[],
  title?: string,
  filename = 'yeen-paper.pdf'
) {
  // Logic check: Ensure we aren't running this on the server
  if (typeof window === 'undefined') return;

  const doc = <ExamPDFDocument questions={questions} title={title} />;
  const blob = await pdf(doc).toBlob();
  const url = URL.createObjectURL(blob);
  
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a); // Better compatibility
  a.click();
  
  setTimeout(() => {
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }, 100);
}